### ISSUE TITLE
react-native example doesn't appear to be working

### ISSUE THREAD

**Issue by TheKeenestKeen** [bufbuild/connect-es-integration#601]
I've installed and ran the example project and installed Expo-Go. The following is logged to the terminal in my code editor after entering text in the mobile UI: `ConnectError: [internal] FileReader.readAsArrayBuffer is not implemented`

I appear to have followed the README step by step, so I'm not too sure how to resolve this.

**Comment by smaye81** [comment]
This is actually due to a limitation in React-Native and their lack of support for `FileReader.readAsArrayBuffer`. See the PR [here](https://github.com/facebook/react-native/pull/30769).

This actually used to work in the past for unary requests, but something may have changed in our Connect repo that is causing this to now fail for unary requests also. We also have this [issue](https://github.com/bufbuil) to track with a possible workaround if it helps at all.

**Comment by TheKeenestKeen** [comment]
Thanks

**Comment by smaye81** [comment]
No problem, apologies for the inconvenience. I will update this repo to make more detailed mention of this issue for react-native.

**Comment by TheKeenestKeen** [comment]
Much appreciated. I applied the patch for `FileReader.readAsArrayBuffer` and I can successfully communicate with the remote server at `https://demo.connect.build` using the react-native example. However, if I point the application to one of my locally running express servers (from this repo), I get a message `ConnectError: [internal] Network request failed`. Is there a way to configure the server such that it behaves in a way similar to the remote server at `https://demo.connect.build`?

An example in the README showing this working with a local server would be greatly appreciated.

**Comment by timostamm** [comment]
If the example does not work, we have to either fix up the code causing the issue, or remove the example.

**Comment by smaye81** [comment]
Connect does not currently work at all with React Native, so we can either:

- remove this example altogether until React Native fully supports Fetch
- use the example XHR Transport that was posted in https://github.com/bufbuild/connect-es/issues/199. I tested this and it allows both unary and server-streaming to work.

@timostamm how you want to proceed.

**Comment by timostamm** [comment]
@smaye81, the example XHR Transport is great. I think it's an excellent example for implementing a Transport. In that sense, it fits well with the other examples in this repository. Let's add it here.

I'm sure @Madumo won't mind (but please let us know if you do, Mathieu).

**Comment by smaye81** [comment]
Added the custom transport in [PR 602](https://github.com/bufbuild/connect-es-integration/pull/602).

**Comment by smaye81** [comment]
@TheKeenestKeen re: your network issue, can you provide some more error details? Is there a stack trace showing what is occurring?

**Comment by TheKeenestKeen** [comment]
Sorry for the late response @smaye81. I applied the patch as described in this post https://github.com/facebook/react-native/issues/34402#issuecomment-1449423649 to the react-native example in this repo. This seems to work when pointing to the remote Eliza server (app works as expected), but when I spin up the express server from this repo and point the mobile client to the express server at https://localhost:3000, I get the following:

```[Unhandled promise rejection: ConnectError: [internal] Network request failed]
at node_modules/@bufbuild/connect/dist/cjs/connect-error.js:1:13 in <global>
at node_modules/@bufbuild/connect/dist/cjs/connect-error.js:42:8 in ConnectError#constructor
at node_modules/@bufbuild/connect/dist/cjs/connect-error.js:107:31 in connectErrorFromReason
at node_modules/@bufbuild/connect-web/dist/cjs/connect-transport.js:80:58 in unary
- ... 8 more stack frames from framework internals
```

What I did above was just a stab in the dark to see if I could get something working and it is unrelated to the approach in the current open PR in this repo. Please ignore my approach above.

**Comment by smaye81** [comment]
Hi @TheKeenestKeen.  Instead of using `localhost`, try using the IP address of the machine that is running the Express server. That should hopefully work.

Also, are you running on iOS or Android?  Apple disables HTTP requests by default, so if you want this to be more of a long-term thing, see docs [here](https://reactnative.dev/docs/integration-with-existing-apps.html?language=objc#1-add-app-transport-security-exception).

**Comment by TheKeenestKeen** [comment]
Thanks @smaye81 -- using the IP address instead got it working! I'm working on Android at the moment.

**Comment by smaye81** [comment]
Great!  Going to close this issue, but if you encounter any other problems, feel free to open a new issue.
