### ISSUE TITLE
Please add a golang server

### ISSUE THREAD

**Issue by anborg** [bufbuild/connect-es-integration#761]

**Comment by smaye81** [comment]
Hi @anborg. This repo is mainly to show Connect-ES functionality at work (web and Node.js) and it focuses on TypeScript/JavaScript only. However, all of the examples in the repo interact with our Connect Demo server, which is written in Go. The repo for the server is here: https://github.com/bufbuild/connect-demo

You can also interact with the server via https://demo.connect.build.
